version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: redditclone
    ports:
      - "3306:3306"
    volumes:
      - './sql/:/docker-entrypoint-initdb.d/'
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_DATABASE=redditclone
    ports:
      - '27017:27017'